# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(954, 794)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 0, 641, 41))
        self.label.setObjectName("label")
        self.textBrowser_before = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_before.setGeometry(QtCore.QRect(30, 80, 411, 581))
        self.textBrowser_before.setObjectName("textBrowser_before")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 50, 441, 631))
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(460, 50, 481, 631))
        self.groupBox_2.setObjectName("groupBox_2")
        self.textBrowser_after = QtWidgets.QTextBrowser(self.groupBox_2)
        self.textBrowser_after.setGeometry(QtCore.QRect(20, 30, 451, 581))
        self.textBrowser_after.setObjectName("textBrowser_after")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(230, 690, 461, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_chooseFile = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_chooseFile.setObjectName("btn_chooseFile")
        self.horizontalLayout.addWidget(self.btn_chooseFile)
        self.btn_covert = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_covert.setObjectName("btn_covert")
        self.horizontalLayout.addWidget(self.btn_covert)
        self.groupBox_2.raise_()
        self.groupBox.raise_()
        self.label.raise_()
        self.textBrowser_before.raise_()
        self.horizontalLayoutWidget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 954, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "软件功能：将语雀导出为markdown，打开导出的markdown文件，可以将内部无法显示图片链接转换为可以显示的外链接"))
        self.groupBox.setTitle(_translate("MainWindow", "转换前"))
        self.groupBox_2.setTitle(_translate("MainWindow", "转换后"))
        self.btn_chooseFile.setText(_translate("MainWindow", "选择md文件"))
        self.btn_covert.setText(_translate("MainWindow", "开始转换"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
